version: 2.1

executors:
  jdk8:
    docker:
      - image: gradle:6.9.2-jdk8

jobs:
  build:
    executor: jdk8
    steps:
      - checkout
      - run: gradle clean bootJar
  test:
    executor: jdk8
    steps:
      - checkout
      - run: gradle test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: build/reports/jacoco/test/html

workflows:
  integrate:
    jobs:
      - build
      - test:
          requires:
            - build
